#!/usr/bin/env python3
"""
Convert a meeting-prep markdown briefing to a styled HTML email and send via Resend.

Usage:
    python3 send-email.py <markdown-file> [--to email] [--subject "Subject"]
    python3 send-email.py --date 2026-03-11  # auto-finds ~/Desktop/meeting-prep-2026-03-11.md

Reads RESEND_API_KEY from environment or Vault via get-secret.sh.
Reads DEFAULT_TO from environment variable MEETING_PREP_TO or prompts.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.request
from datetime import date, datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Config — all values from environment, no hardcoded user-specific defaults
# ---------------------------------------------------------------------------
# DEFAULT_TO: set via MEETING_PREP_TO env var, or pass --to on the command line.
# If neither is set, the script will error with a helpful message.
DEFAULT_TO = os.environ.get("MEETING_PREP_TO", "")
# FROM_ADDRESS: set via MEETING_PREP_FROM env var, or override with a default.
FROM_ADDRESS = os.environ.get("MEETING_PREP_FROM", "Outwork OS <briefing@outworkai.co>")
OUTWORKOS_ROOT = os.environ.get("OUTWORKOS_ROOT", "")


def get_api_key() -> str:
    key = os.environ.get("RESEND_API_KEY")
    if key:
        return key
    if not OUTWORKOS_ROOT:
        print(
            "Error: OUTWORKOS_ROOT not set and RESEND_API_KEY not in environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    get_secret = os.path.join(OUTWORKOS_ROOT, "scripts", "get-secret.sh")
    try:
        return subprocess.check_output([get_secret, "resend_api_key"], text=True).strip()
    except Exception as e:
        print(f"Error retrieving Resend API key: {e}", file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# Markdown -> HTML conversion (no external deps beyond stdlib + markdown)
# ---------------------------------------------------------------------------
def md_to_html_body(md_text: str) -> str:
    """Convert meeting-prep markdown to HTML paragraphs with minimal deps."""
    import markdown

    # Convert with basic extensions
    html = markdown.markdown(md_text, extensions=["extra"])
    return html


def wrap_in_email_template(body_html: str, title: str) -> str:
    """Wrap HTML body in a responsive, email-client-friendly template."""
    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
</head>
<body style="margin:0; padding:0; background-color:#f4f4f7; font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f7;">
<tr><td align="center" style="padding:32px 16px;">

<!-- Container -->
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px; background-color:#ffffff; border-radius:8px; overflow:hidden; box-shadow:0 1px 4px rgba(0,0,0,0.08);">

<!-- Header -->
<tr>
<td style="background-color:#1a1a2e; padding:24px 32px;">
  <p style="margin:0; font-size:13px; letter-spacing:1.5px; text-transform:uppercase; color:#8888aa; font-weight:600;">Outwork OS</p>
  <h1 style="margin:8px 0 0; font-size:22px; font-weight:600; color:#ffffff; line-height:1.3;">{title}</h1>
</td>
</tr>

<!-- Body -->
<tr>
<td style="padding:28px 32px 36px;">
  <style>
    .briefing h1 {{ font-size:20px; font-weight:600; color:#1a1a2e; margin:32px 0 12px; line-height:1.3; }}
    .briefing h2 {{ font-size:17px; font-weight:600; color:#1a1a2e; margin:28px 0 12px; padding-top:20px; border-top:1px solid #e8e8ee; line-height:1.3; }}
    .briefing h2:first-child {{ border-top:none; padding-top:0; margin-top:0; }}
    .briefing p {{ font-size:15px; line-height:1.7; color:#2d2d3a; margin:0 0 14px; }}
    .briefing hr {{ border:none; border-top:1px solid #e8e8ee; margin:24px 0; }}
    .briefing strong {{ color:#1a1a2e; }}
    .briefing a {{ color:#4a6cf7; text-decoration:none; }}
    .briefing ul, .briefing ol {{ font-size:15px; line-height:1.7; color:#2d2d3a; padding-left:20px; }}
    .briefing li {{ margin-bottom:6px; }}
    .briefing blockquote {{ border-left:3px solid #4a6cf7; padding:8px 16px; margin:16px 0; background:#f8f8fc; color:#4a4a5a; font-style:italic; }}
  </style>
  <div class="briefing">
    {body_html}
  </div>
</td>
</tr>

<!-- Footer -->
<tr>
<td style="padding:16px 32px 24px; border-top:1px solid #e8e8ee;">
  <p style="margin:0; font-size:12px; color:#9999aa; line-height:1.5;">
    Generated by Outwork OS &middot; Meeting Prep<br>
    {datetime.now().strftime("%A, %B %-d, %Y at %-I:%M %p")}
  </p>
</td>
</tr>

</table>
<!-- /Container -->

</td></tr>
</table>

</body>
</html>"""


# ---------------------------------------------------------------------------
# Send via Resend API
# ---------------------------------------------------------------------------
def send_email(api_key: str, to: str, subject: str, html: str) -> dict:
    payload = json.dumps({
        "from": FROM_ADDRESS,
        "to": [to],
        "subject": subject,
        "html": html,
    }).encode()

    req = urllib.request.Request(
        "https://api.resend.com/emails",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "User-Agent": "OutworkOS/1.0",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read().decode())
            return result
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"Resend API error {e.code}: {body}", file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# Parse subject from markdown
# ---------------------------------------------------------------------------
def extract_title(md_text: str) -> str:
    """Pull the H1 title from the markdown, or generate a date-based one."""
    match = re.match(r"^#\s+(.+)$", md_text.strip(), re.MULTILINE)
    if match:
        return match.group(1).strip()
    return f"Meeting Prep — {date.today().strftime('%A, %B %-d')}"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Send meeting-prep briefing via Resend")
    parser.add_argument("file", nargs="?", help="Path to the markdown briefing file")
    parser.add_argument("--date", help="Date to find briefing for (YYYY-MM-DD), looks in ~/Desktop/")
    parser.add_argument("--to", default=DEFAULT_TO, help="Recipient email (env: MEETING_PREP_TO)")
    parser.add_argument("--subject", help="Email subject (default: extracted from markdown H1)")
    parser.add_argument("--dry-run", action="store_true", help="Print HTML to stdout instead of sending")
    args = parser.parse_args()

    if not args.to:
        print(
            "Error: No recipient specified. Set MEETING_PREP_TO env var or pass --to.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Resolve file path
    if args.file:
        md_path = Path(args.file)
    elif args.date:
        md_path = Path.home() / "Desktop" / f"meeting-prep-{args.date}.md"
    else:
        # Default: today's file
        today = date.today().isoformat()
        md_path = Path.home() / "Desktop" / f"meeting-prep-{today}.md"

    if not md_path.exists():
        print(f"Briefing file not found: {md_path}", file=sys.stderr)
        sys.exit(1)

    md_text = md_path.read_text()
    subject = args.subject or extract_title(md_text)
    body_html = md_to_html_body(md_text)
    full_html = wrap_in_email_template(body_html, subject)

    if args.dry_run:
        print(full_html)
        return

    api_key = get_api_key()
    result = send_email(api_key, args.to, subject, full_html)
    print(f"Email sent via Resend (id: {result.get('id', 'unknown')})")


if __name__ == "__main__":
    main()
